name: Run Pytest, Flake8, and Mypy

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flake8
          pip install mypy
          pip install types-requests
          pip install python-telegram-bot httpx

      - name: Run flake8 linter
        run: |
          flake8 . --exclude=venv --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --exclude=venv --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run mypy type checks
        run: |
          mypy .

      - name: Run pytest
        run: |
          python -m pytest tests/ --maxfail=3 --disable-warnings -v 